# This is a basic workflow to help you get started with Actions

name: armTemplateDeployRG1

# Controls when the workflow will run

on:
  workflow_dispatch:
env:
  subscriptionId: d115c59d-1362-424a-b30d-a254b28c46bb
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      resource_group_name: ArmDemo
      location: Central US
    environment:
      name: staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: az login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZ_CREDS}}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-template/arm-template1.json
          parameters:
            location="${{ env.location }}"
            rg-name=${{ env.resource_group_name }}

          deploymentName: ${{ env.resource_group_name }}
